// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vcivrvktkigeezoqekfm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZjaXZydmt0a2lnZWV6b3Fla2ZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxNDgyOTcsImV4cCI6MjA2ODcyNDI5N30.cuuU2qzYJZXFX9RV4NgFJao16PK3kyzv-syy2aDNmgk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});